server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: messages
          uri: http://127.0.0.1:8070
          predicates:
            - Path=/messages/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: resource
          uri: http://127.0.0.1:8090
          predicates:
             - Path=/resource/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie



  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,profile,message.read,message.write
        provider:
          spring:
            issuer-uri: http://localhost:9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO
